#####################################################
###     VECTOR OF MODELS USED IN ANALYSES   #########
#####################################################

# This script is simply a list of models used in CEMML analyses
# It is used with the 'steps' script to enable easy variable naming


models <- c("HADGEM2-ES", 
            "LOCA_CCSM4", 
            "MACA_CCSM4",
            "MACA_CCSM4_Monthly",
            "MIROC6",     
            "MPI-ESM1-2-HR",
            "EC-Earth3-Veg-LR",
            "ACCESS-ESM1-5")


shp_names <- c("Homestead_ARB", 
              "Guam_Proxy_v1", # Navy
              "CNMI_Proxy_v1", # Navy
              "Indianhead_Proxy", # Navy
              "JBER",                   
              "Dugway_Proving_Grounds",
              "Hill_AFB_Boundary",
              "LMTF_Boundary",
              "HAMOTS_Boundary",
              "Park_City_Property_Boundary", 
              "PSRF_Boundary",
              "South_Range_Boundary",
              "Carter_Creek_Recreation_Center_Boundary",
              "JBLE_L",
              "JBLE_E",
              "Edwards_AFB",                 
              "Malmstrom_AFB_Proxy",
              "Kitsap_Proxy",
              "NB_SanDiego_Proxy",
              "NAS Oceana",
              "Nellis_AFB",                  
              "NTTR - Central",
              "NTTR - North",
              "NTTR - South",
              "Creech_AFB",
              "Ascension Island",             
              "Eareckson_AFB",
              "Eielson_AFB",
              "Eglin_Niceville",
              "CapeCanaveral_45th",
              "Malibar_45th",              
              "45th SW - JDMTA",
              "JBER",
              "Edwards_AFB",
              "JBMDL", 
              "Edwards_AFB_v2",
              "Edwards_AFB_v3_EastofBarstow",
              "Edwards_AFB_v3_Renoville",
              "JBMDL",
              "Luke Aux Air Field",
              "BMGR_East",
              "BMGR_West",
              "BGR_West_Marines", # actual name of shp in folder 9-10-2025
              "BGR-W", # Desired name for outputs 9-10-2025
              "Dover_AFB",
              "New Boston SFS",
              "45th SW - Cape Canaveral",
              "Luke_AFB",
              "Luke_AFB_FTRA",
              "Dover_AFB",
              "NewBoston_SFS",
              "Travis_AFB",
              "Travis_AFB_Ozol",
              "Beale_AFB",
              "Naval_Station_Norfolk",
              "NCTAMS_Cutler",
              "RAF_Alconbury_and_RAF_Molesworth",
              "Holloman_Air_Force_Base",
              "611_-_King_Salmon_Airport",
              "NWS_Yorktown",
              "NSA_Panama_City",
              "611_-_Cold_Bay_Long_Range_Radar_Site",
              "611_-_Indian_Mountain",
              "NAS_Jacksonville",
              "Pituffik_SB")           


official_base_names <- c("NAVBASE Kitsap",     
                                   "NAVBASE San Diego",
                                   "Naval Air Station Oceana",
                                   "Nellis Air Force Base",
                                   "Nevada Test and Training Range - Central",   
                                   "Nevada Test and Training Range - North",
                                   "Nevada Test and Training Range - South",
                                   "Creech Air Force Base",
                                   "Ascension Island",
                                   "Eareckson Air Force Station",                 
                                   "Eielson Air Force Base",
                                   "Eglin Air Force Base",
                                   "Malibar Transmitter Annex",
                                   "Jonathan Dickinson Missile Tracking Annex",
                                   "Joint Base Elmendorf-Richardson", 
                                   "Edwards Air Force Base",
                                   "Joint Base McGuire-Dix-Lakehurst",
                                   "Joint Base Langley-Eustis - Langley Air Force Base",
                         "Joint Base Langley-Eustis - Fort Eustis",
                         "Luke Air Force Auxiliary Field No 1",
                         "Luke Air Force Base",
                         "Barry Goldwater Range (West)", # Marines
                         "Barry M. Goldwater Range (Zone 1)", # West
                         "Barry M. Goldwater Range (Zone 2)", # East
                         "Dover Air Force Base",
                         "New Boston Space Force Station",
                         "45 Space Wing - Cape Canaveral Space Force Station",
                         "45 Space Wing - JDMTA",
                         "Luke Air Force Base",
                         "Luke Air Force Base - Fort Tuthill Recreation Area",
                         "Dover Air Force Base",
                         "New Boston Space Force Station",
                         "Travis Air Force Base",
                         "Travis Air Force Base - Ozol",
                         "Beale Air Force Base",
                         "Naval Station Norfolk",
                         "NSA Cutler",
                         "RAF Alconbury and RAF Molesworth",
                         "Holloman Air Force Base",
                         "King Salmon Airport",
                         "Naval Weapons Station Yorktown",
                         "NSA Panama City",
                         "Cold Bay Long Range Radar Site",
                         "Indian Mountain Air Force Station",
                         "Naval Air Station Jacksonville",
                         "Pituffik Space Force Base") 
                        