#####################################################
###     VECTOR OF MODELS USED IN ANALYSES   #########
#####################################################

# This script is simply a list of models used in CEMML analyses
# It is used with the 'steps' script to enable easy variable naming


models <- c("HADGEM2-ES", 
            "LOCA_CCSM4", 
            "MACA_CCSM4",
            "MACA_CCSM4_Monthly",
            "MIROC6",     
            "MPI-ESM1-2-HR",
            "EC-Earth3-Veg-LR",
            "ACCESS-ESM1-5")


shp_names <- c("Homestead_ARB", 
              "Guam_Proxy_v1", # Navy
              "CNMI_Proxy_v1", # Navy
              "Indianhead_Proxy", # Navy
              "JBER",                   
              "Dugway_Proving_Grounds",
              "Hill_AFB_Boundary",
              "LMTF_Boundary",
              "HAMOTS_Boundary",
              "Park_City_Property_Boundary", 
              "PSRF_Boundary",
              "South_Range_Boundary",
              "Carter_Creek_Recreation_Center_Boundary",
              "JBLE_L",
              "JBLE_E",
              "Edwards_AFB",                 
              "Malmstrom_AFB_Proxy",
              "Kitsap_Proxy",
              "NB_SanDiego_Proxy",
              "NAS Oceana",
              "Nellis_AFB",                  
              "NTTR - Central",
              "NTTR - North",
              "NTTR - South",
              "Creech_AFB",
              "Ascension Island",             
              "Eareckson_AFB",
              "Eielson_AFB",
              "Eglin_Niceville",
              "CapeCanaveral_45th",
              "Malibar_45th",              
              "45th SW - JDMTA",
              "JBER",
              "Edwards_AFB",
              "JBMDL", 
              "Edwards_AFB_v2",
              "Edwards_AFB_v3_EastofBarstow",
              "Edwards_AFB_v3_Renoville",
              "JBMDL",
              "Luke Aux Air Field",
              "BMGR",
              "Dover AFB",
              "New Boston SFS",
              "45th SW - Cape Canaveral",
              "Luke AFB")             
               "Guam_Proxy_v1", # Navy
               "CNMI_Proxy_v1", # Navy
               "Indianhead_Proxy", # Navy
               "JBER",                   
               "Dugway_Proving_Grounds",
               "Hill_AFB_Boundary",
               "LMTF_Boundary",
               "HAMOTS_Boundary",
               "Park_City_Property_Boundary", 
               "PSRF_Boundary",
               "South_Range_Boundary",
               "Carter_Creek_Recreation_Center_Boundary",
               "JBLE_L",
               "JBLE_E",
               "Edwards_AFB",                 
               "Malmstrom_AFB_Proxy",
               "Kitsap_Proxy",
               "NB_SanDiego_Proxy",
               "NAS Oceana",
               "Nellis_AFB",                  
               "NTTR - Central",
               "NTTR - North",
               "NTTR - South",
               "Creech_AFB",
               "Ascension Island",             
               "Eareckson_AFB",
               "Eielson_AFB",
               "Eglin_Niceville",
               "CapeCanaveral_45th",
               "Malibar_45th",              
               "45th SW - JDMTA",
               "JBER",
               "Edwards_AFB",
               "JBMDL", 
               "Edwards_AFB_v2",
               "Edwards_AFB_v3_EastofBarstow",
               "Edwards_AFB_v3_Renoville",
               "JBMDL",
               "Luke Aux, Air Field",
               "BMGR",
               "Dover AFB",
               "New Boston SFS",
               "45th SW - Cape Canaveral",
               "Luke AFB")             


official_base_names <- c("NAVBASE Kitsap",     
                                   "NAVBASE San Diego",
                                   "Naval Air Station Oceana",
                                   "Nellis Air Force Base",
                                   "Nevada Test and Training Range - Central",   
                                   "Nevada Test and Training Range - North",
                                   "Nevada Test and Training Range - South",
                                   "Creech Air Force Base",
                                   "Ascension Island",
                                   "Eareckson Air Force Station",                 
                                   "Eielson Air Force Base",
                                   "Eglin Air Force Base",
                                   "Malibar Transmitter Annex",
                                   "Jonathan Dickinson Missile Tracking Annex",
                                   "Joint Base Elmendorf-Richardson", 
                                   "Edwards Air Force Base",
                                   "Joint Base McGuire-Dix-Lakehurst",
                                   "Joint Base Langley-Eustis - Langley Air Force Base",
                         "Joint Base Langley-Eustis - Fort Eustis",
                         "Luke Air Force Auxiliary Field No 1",
                         "Luke Air Force Base",
                         "The Barry M Goldwater Air Force Range",
                         "Dover Air Force Base",
                         "New Boston Space Force Station",
                         "45 Space Wing - Cape Canaveral Space Force Station",
                         "45 Space Wing - JDMTA") 
                         "NAVBASE San Diego",
                         "Naval Air Station Oceana",
                         "Nellis Air Force Base",
                         "Nevada Test and Training Range - Central",   
                         "Nevada Test and Training Range - North",
                         "Nevada Test and Training Range - South",
                         "Creech Air Force Base",
                         "Ascension Island",
                         "Eareckson Air Force Station",                 
                         "Eielson Air Force Base",
                         "Eglin Air Force Base",
                         "Malibar Transmitter Annex",
                         "Jonathan Dickinson Missile Tracking Annex",
                         "Joint Base Elmendorf-Richardson", 
                         "Edwards Air Force Base",
                         "Joint Base McGuire-Dix-Lakehurst",
                         "Joint Base Langley-Eustis - Langley Air Force Base",
                         "Joint Base Langley-Eustis - Fort Eustis",
                         "Luke Air Force Auxiliary Field No 1",
                         "Luke Air Force Base",
                         "The Barry M Goldwater Air Force Range",
                         "Dover Air Force Base",
                         "New Boston Space Force Station",
                         "45 Space Wing - Cape Canaveral Space Force Station",
                         "45 Space Wing - JDMTA") 




